version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "22558:22558"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: csv-merger
    ports:
      - "8000:8000"
    environment:
    # Below mongodb URI comes from railway mongodb database,  
      - MONGODB_URI=mongodb://mongo:itROjvcqxULJHfnbxvxTvXgUCJNktgom@monorail.proxy.rlwy.net:22558
    depends_on:
      - mongodb

volumes:
  mongo-data:
